function randomTitle() {
    var choose = Array(
"NO hidden blocks. Studies claim fun has increased by 200%!",
"Even though mushrooms exist, koopas aren't real.",
"figment of myself",
"The fuck are you?",
"Is this a for real moment?",
"Jarvis, steal someone's Caterpillar script.",
"(tears)",
"Nothing more than a dog of the gods.",
"Guys, is it bullying if I beat someone 30-3?",
"'Legendary Illusion', litteraly, i'm not real.",
"A comma forgotten and 2 hours losttt.",
"embodiment of skill issue",
"mini-mushroom is my favorite power-up!!!",
"Trans rights!",
"I'm so mad, I'm so mad I'm going to have sex with my girlfriend",
"Getting the 120 stars won't save Claus",
"Removing the Seven Needles won't unlock Luigi",
"Now, where were we?",
"マリオたちは大変なものを盗まれていきました",
"www",
"Highly Unresponsible to Feedback",
"Legacy of the Autistic Kingdom",
"Imperishable Hyperfixation",
"Ten Desires: a N3DSXL, Super Mario 3D Lan...",
"I'm uninspired rn",
"I do hope it gets randomized, otherwise I'm wasting my time",
"There's no such thing as a Nintendo.",
"News: There's a website",
"News: Look behind you.",
"News: Someone fucking died.",
"3.141592653589793238462643383279502884197",
"It could be me, it could be you.",
"It's going to be a long night.",
"It's going to be a fun night.",
"88888888",
"1 2 2 50",
"I II II L",
"You lost The Game",
"Spending 3 years of your life for a 350th place on speedrun.com",
" (＃￣0￣)",
"based? based on what?",
"accidental homicide",
"LeBron James reportedly ranks Touhou EOSD as the best game in the series",
"Oops, accidentaly broke the website (; ^^)",
"oh shit waddup",
"The Mario movie was okay in my opinion",
    );
    var rand = Math.floor(Math.random() * choose.length);
    document.title = choose[rand];
}
